entrypoint: "gunicorn -b :$PORT main:app --timeout 500"
runtime: python
env: flex
service: img-detection
runtime_config:
  python_version: 3.7
instance_class: B1
manual_scaling:
  instances: 1
liveness_check:
  path: "/liveness_check"